# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1c4456182c09b2355b2a44d79de34be398f365610d21eca33a531393b7fec6945ae4ffc0694e8539edee2865f19f7b9175a776d9a1b167e98639b50f4cb74f5

test:
  secret_key_base: e5d65c43995509f960a9facafb545af3cab95eb4fd2a7ac47b9dd59cba15c4b55e623ff98e821b4211ccb530a6cf02ed16356fb0d4288e95d7773a8e1f104003

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
